### ISSUE TITLE
expose port to ip hosts

### ISSUE THREAD

**Issue by ghost** [mustafaileri/redis-cluster-with-sentinel#1]
hi mustafaileri ..

thanks for sharing this project. 

how i can expose port redis master to port host machine ?? 

basicly in docker when i want to exposed port like this

docker run -d --name redis **-p 6379:6379** redis

thanks you

**Comment by mustafaileri** [comment]
Hi @skythink. Yo can do it in docker-compose.yml. 
But if you can define a port mapping, you can not scale system. Because Ports will be conflicts when you scale up.
